version: "3.8"
services:
    web:
        build: ./project
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - ./project/:/usr/src/project/
        ports:
            - 8000:8000
        environment:
            - DB_NAME=vehicle_repairs_db
            - DB_USER=postgres
            - DB_PASSWORD=admin123
            - DB_HOST=pg
            - DB_PORT=5432
            - DATABASE=postgres
        depends_on:
          pg:
            condition: service_healthy
    pg:
        container_name: pg_container
        image: postgres:13.2-alpine
        restart: always
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: admin123
            POSTGRES_DB: vehicle_repairs_db
            POSTGRES_HOST_AUTH_METHOD: trust
        ports:
            - "5432:5432"
        volumes:
            - ./data:/data
            - ./data/misc/django_init.sql:/docker-entrypoint-initdb.d/1-django-init.sql
        healthcheck :
          test: [ "CMD", "pg_isready", "-q", "-d", "vehicle_repairs_db", "-U", "postgres" ]
          interval : 60s
          timeout : 60s
          retries : 5
    pgadmin:
        container_name: pgadmin_container
        image: dpage/pgadmin4:5.2
        restart: always
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@example.com
            PGADMIN_DEFAULT_PASSWORD: admin123
            PGADMIN_LISTEN_PORT: 5433
            PGADMIN_CONFIG_SERVER_MODE: "False"
            PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "False"
        ports:
            - "5433:5433"
        depends_on:
            - pg
