name: Vehicle Repairs App Pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    
      - name: Get repo
        uses: actions/checkout@v2
        
      - run: echo Entering CI/CD Pipeline!

      - name: Install Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9         

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt
 
      - name: Run migrations
        run: python manage.py migrate
    
      - name: Run all tests
        run: pytest -v
